[package]
name = "ElaWidgetToolsExample"
version = "1.0.0"

[dependencies]
ElaWidgetTools = { path = "../ElaWidgetTools", linkage = "shared" }

[build-dependencies]
mcpp.plugins = { version = "0.18.1", features = ["rules-qt"], host-module = true }

[build]
default-profile = "release"
sources = ["**/*.cpp", "!main.cpp"]
include_dirs = [".", "ExamplePage", "ModelView", "../ElaWidgetTools"]

[targets.ElaWidgetToolsExample]
kind = "bin"
main = "main.cpp"
windows_subsystem = "windows"
